services:
  - type: web
    runtime: static
    name: cfm-energy-website
    staticPublishPath: .
    domains:
      - cfm.energy
      - www.cfm.energy
    headers:
      - path: /*
        name: X-Robots-Tag
        value: noindex, nofollow, noarchive, nosnippet
